name: Build

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        runner: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v21
        with:
          determinate: false
      - run: nix flake check --print-build-logs
